image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pypoetry"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - .cache/pypoetry/virtualenvs

before_script:
  - python -V  # Print out python version for debugging
  - pip install poetry
  - cd $CI_PROJECT_DIR
  - poetry install
  - poetry build

unit_tests:
  stage: test
  script:
    - poetry run pytest test/unit/ --cov=awesomedl

mypy_tests:
  stage: test
  script:
    - poetry run pytest --mypy -m mypy

func_tests:
  stage: test
  before_script:
    - pip install poetry
    - cd $CI_PROJECT_DIR
    - poetry install
    - source $(poetry env info -p)/bin/activate 
    - mkdir -p $HOME/.config/awesome/ytdl
    - python -m uvicorn awesomedl.main:app --host 127.0.0.1 --port 8080 > /dev/null 2>&1 &
    - echo $! > PIDFILE
  script:
    - poetry run pytest test/fun
  after_script:
    - test -e PIDFILE && kill $(cat PIDFILE)
    - test -e PIDFILE && rm PIDFILE
