[tool.poetry]
name = "awesome-dl"
version = "0.1.0"
description = ""
authors = ["Cameron Ruatta <c@ruatta.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
fastapi = "^0.54.1"
youtube-dl = "^2020.5.8"
pebble = "^4.5.0"
pathos = "^0.2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
