version: 2.1

jobs:
  setup:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          command: pip install poetry
      - run:
          command: poetry install
